# Generated by Django 3.2.23 on 2024-01-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Post Title')),
                ('thumbnail', models.ImageField(upload_to='images/product', verbose_name='Post Thumbnail')),
                ('video', models.FileField(upload_to='uploads/uploaded_videos', verbose_name='Post Video')),
                ('description', models.TextField(db_index=True, verbose_name='Post description')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='Post slug')),
                ('is_active', models.BooleanField(default=False, verbose_name='is/is not active')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
