# Generated by Django 3.2.23 on 2024-01-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0005_auto_20240122_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='channel',
        ),
    ]
