# Generated by Django 3.2.23 on 2024-01-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0006_rename_creator_post_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='channel',
            new_name='creator',
        ),
    ]
