# Generated by Django 3.2.23 on 2024-02-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0013_postcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomments',
            options={'verbose_name': 'Post Comment', 'verbose_name_plural': 'Post Comments'},
        ),
        migrations.AlterModelOptions(
            name='postviews',
            options={'verbose_name': 'Post visit', 'verbose_name_plural': 'Post visits'},
        ),
    ]
