# Generated by Django 3.2.23 on 2024-02-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0014_auto_20240206_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_module.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='text',
            field=models.CharField(max_length=10000, verbose_name='comment Text'),
        ),
    ]
