# Generated by Django 3.2.23 on 2024-02-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0017_auto_20240216_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='video',
        ),
        migrations.AddField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='post_module.Post', verbose_name='Video'),
        ),
    ]
