# Generated by Django 3.2.23 on 2024-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0018_auto_20240216_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is/is not active'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(to='post_module.Post', verbose_name='Video'),
        ),
    ]
