# Generated by Django 3.2.23 on 2024-02-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0019_auto_20240216_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='playlist',
            field=models.ManyToManyField(to='post_module.Playlist', verbose_name='Playlist'),
        ),
    ]
