# Generated by Django 3.2.23 on 2024-02-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0022_auto_20240217_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='Playlist slug'),
        ),
    ]
