# Generated by Django 3.2.23 on 2024-02-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0025_alter_playlist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='video',
        ),
        migrations.AddField(
            model_name='playlist',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post_module.post', verbose_name='Video'),
        ),
        migrations.DeleteModel(
            name='PlaylistVideo',
        ),
    ]
