# Generated by Django 3.2.23 on 2024-02-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0026_auto_20240222_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='video',
        ),
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post_module.playlist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post_module.post')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='video',
            field=models.ManyToManyField(through='post_module.PlaylistVideo', to='post_module.Post', verbose_name='Video'),
        ),
    ]
