# Generated by Django 3.2.23 on 2024-02-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0027_auto_20240222_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
