# Generated by Django 5.1.1 on 2025-02-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0034_alter_postcomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
