# Generated by Django 5.1.1 on 2025-03-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0035_playlist_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviews',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
