# Generated by Django 3.2.23 on 2024-01-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_banner',
            field=models.ImageField(blank=True, null=True, upload_to='Profiles/Channel_banner'),
        ),
    ]
